name: CI Build

on:
  push:
    # branches: [ develop, feature/** ]
    branches: [ releaseNotes ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: UI Install
        run: yarn --cwd ./src/Ombi/ClientApp install

      - name: Build and Publish UI
        run: yarn --cwd ./src/Ombi/ClientApp run build

      - name: Publish UI Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            ./src/Ombi/ClientApp/dist/

      - name: Run Unit Tests
        run: dotnet test .\src\Ombi.sln
