name: Automation Tests

on:
  push:
    branches: [ feature/automation ]
  pull_request:
    branches: [ feature/automation ]

jobs:
  automation-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Start Server
      run: |
          dotnet run -p ./src/Ombi -- --host http://*:3577 &
          yarn --cwd ./src/ombi/clientapp start
    - name: Cypress Tests
      uses: cypress-io/github-action@v2.8.2
      with:
        browser: chrome
        headless: true
        project: ./tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

