name: Automation Tests

on:
  push:
    branches: [ feature/automation ]
  pull_request:
    branches: [ feature/automation ]

jobs:
  automation-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install FrontEnd Deps
      run: yarn --cwd ./src/Ombi/ClientApp install

    - name: Start Backend
      run: |
          nohup run -p ./src/Ombi -- --host http://*:3577 &

    - name: Start Frontend
      run: |
          nohup yarn --cwd ./src/Ombi/ClientApp start &

    - name: Cypress Tests
      uses: cypress-io/github-action@v2.8.2
      with:
        browser: chrome
        headless: true
        project: ./tests
        wait-on: http://localhost:3577/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

